const actionTypes = {
  //General UI
  TOGGLE_SIDEBAR_MENU: "TOGGLE_SIDEBAR_MENU",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",

  //General Information
  SET_LANGUAGE: "SET_LANGUAGE",

  //Movies Page
  CHANGE_MOVIES_TAB: "CHANGE_MOVIES_TAB",

  //Movies requests
  GET_POPULAR_MOVIES: "GET_POPULAR_MOVIES",
  GET_UPCOMING_MOVIES: "GET_UPCOMING_MOVIES",
  GET_NOW_PLAYING_MOVIES: "GET_NOW_PLAYING_MOVIES",
  GET_TOP_RATED_MOVIES: "GET_TOP_RATED_MOVIES",
  CLEAR_MOVIES: "CLEAR_MOVIES",
};

export default actionTypes;
